-- gen.lua: generator for ABC VM 2.0 (active banked interpreter/JIT track).
--
--   lua5.4 gen.lua opcodes     opcodes.h
--   lua5.4 gen.lua interp      vm_bank.c        A/B operand bank + C bank (3 cells)
--   lua5.4 gen.lua interp0     vm_mem.c         nothing cached (baseline)
--   lua5.4 gen.lua jit         stencils_bank.c  JIT stencils, C bank of 4 cells
--   lua5.4 gen.lua jit0        stencils_mem.c   JIT stencils, nothing cached
--
-- Register model (spec, "The operand bank"): A and B share four registers
-- h0..h3. A's cached cells fill the bank from h0 upward and B's from h3
-- downward, so A0 = h[a-1] and B0 = h[4-b]; the free registers form one gap
-- between the two tops. C has its own bank, C0 = c[k-1]. A state is (a, b, k).
-- Pushes and pops move no values; only a push onto a full bank spills.

local MODE, OUT = arg[1], arg[2]
assert(MODE and OUT, "usage: gen.lua opcodes|interp|interp0|jit|jit0 OUT")

------------------------------------------------------------------ opcodes
-- { name, length in bytes, kind }   kinds: n normal, br rel16 branch,
-- call rel32 call, ret, halt, abort
local OPS = {}
local function op(name, len, kind) OPS[#OPS + 1] = { name, len, kind or "n" } end
op("HALT", 1, "halt")
for _, X in ipairs({"A", "B"}) do op("PUSH8_" .. X, 2); op("PUSH32_" .. X, 5); op("PUSH64_" .. X, 9) end
for _, X in ipairs({"A", "B"}) do op("DUP_" .. X, 1); op("DROP_" .. X, 1) end
op("COPY_AB", 1); op("COPY_BA", 1); op("MOVE_AB", 1); op("MOVE_BA", 1)
op("CPUSH_A", 1); op("CPUSH_B", 1); op("CPUSHN", 2); op("CPOP", 1)
for _, X in ipairs({"A", "B"}) do
  op("CGET0_" .. X, 1); op("CGET1_" .. X, 1); op("CGETN_" .. X, 2); op("CGETR_" .. X, 3)
  op("CSET0_" .. X, 1); op("CSETN_" .. X, 2)
end
local BINOPS = { "ADD", "SUB", "MUL", "DIVU", "DIVS", "REMU", "REMS", "AND", "OR", "XOR",
                 "SHL", "SHR", "SAR", "EQ", "NE", "LT", "LE", "LTU", "LEU" }
for _, n in ipairs(BINOPS) do op(n .. "_A", 1); op(n .. "_B", 1) end
for _, n in ipairs({ "NEG", "NOT", "LNOT", "ZX32", "SX32" }) do op(n .. "_A", 1); op(n .. "_B", 1) end
for _, n in ipairs({ "ZX8", "ZX16", "POW", "POWS", "CHKU8", "CHKU16", "CHKU32", "CHKI32", "CHKNN" }) do op(n, 1) end
op("JMP", 3, "br")
for _, X in ipairs({"A", "B"}) do op("JZ_" .. X, 3, "br"); op("JNZ_" .. X, 3, "br") end
for _, n in ipairs({ "BEQ", "BNE", "BLT", "BLE", "BLTU", "BLEU" }) do op(n, 3, "br") end
-- operand forms (decision 11): the second operand is an i8 immediate or a C cell; the result stays on X
local OPI_OPS = { "ADD", "SUB", "MUL", "AND", "OR", "XOR", "SHL", "SHR", "SAR" }
local OPC_OPS = { "ADD", "SUB", "MUL", "XOR" }
for _, n in ipairs(OPI_OPS) do op(n .. "I_A", 2, "opi"); op(n .. "I_B", 2, "opi") end
for _, n in ipairs(OPC_OPS) do op(n .. "C_A", 2, "opc"); op(n .. "C_B", 2, "opc") end
local CBI = { BEQI = "%s == %s", BNEI = "%s != %s", BLTI = "(int64_t)%s < (int64_t)%s", BLEI = "(int64_t)%s <= (int64_t)%s",
  BGTI = "(int64_t)%s > (int64_t)%s", BGEI = "(int64_t)%s >= (int64_t)%s", BLTUI = "%s < %s", BLEUI = "%s <= %s",
  BGTUI = "%s > %s", BGEUI = "%s >= %s" }
for _, n in ipairs({ "BEQI", "BNEI", "BLTI", "BLEI", "BGTI", "BGEI", "BLTUI", "BLEUI", "BGTUI", "BGEUI" }) do op(n, 4, "bri") end
-- frame instructions (spec forms): CALL.X f, n   TCALL f, k, n   RET k, r
op("CALL_A", 6, "call"); op("CALL_B", 6, "call"); op("TCALL", 7, "tcall"); op("RET", 3, "ret"); op("ABORT", 2, "abort")
-- internal quickened forms: the first execution of a spec form rewrites its opcode to the variant
-- with the arity built in, so every handler knows its register moves statically
local MAXN, MAXR = 4, 2
for _, X in ipairs({ "A", "B" }) do for n = 0, MAXN do op(("CALL_%s_%d"):format(X, n), 6, "internal") end end
for k = 0, MAXN do for n = 0, MAXN do op(("TCALL_%d_%d"):format(k, n), 7, "internal") end end
for k = 0, MAXN do for r = 0, MAXR do op(("RET_%d_%d"):format(k, r), 3, "internal") end end

if MODE == "opcodes" then
  local KIND = { n = 0, br = 1, call = 2, ret = 3, halt = 4, abort = 5, opi = 6, opc = 7, bri = 8, tcall = 9, internal = 10 }
  local o = { "/* generated by gen.lua */", "#pragma once", "enum {" }
  for i, p in ipairs(OPS) do o[#o + 1] = ("  OP_%s = %d,"):format(p[1], i - 1) end
  o[#o + 1] = ("  OP_COUNT = %d\n};"):format(#OPS)
  o[#o + 1] = "enum { K_NORMAL, K_BRANCH, K_CALL, K_RET, K_HALT, K_ABORT, K_OPI, K_OPC, K_BRI, K_TCALL, K_INTERNAL };"
  local l, k, nm = {}, {}, {}
  for _, p in ipairs(OPS) do l[#l + 1] = p[2]; k[#k + 1] = KIND[p[3]]; nm[#nm + 1] = '"' .. p[1] .. '"' end
  o[#o + 1] = "static const unsigned char op_len[] = {" .. table.concat(l, ",") .. "};"
  o[#o + 1] = "static const unsigned char op_kind[] = {" .. table.concat(k, ",") .. "};"
  o[#o + 1] = "static const char *const op_name[] = {" .. table.concat(nm, ",") .. "};"
  local f = assert(io.open(OUT, "w")); f:write(table.concat(o, "\n"), "\n"); f:close()
  return
end

local JIT = MODE == "jit" or MODE == "jit0"
local CACHED = MODE == "interp" or MODE == "jit"
local NBANK = CACHED and 4 or 0
local CDEPTH = CACHED and (JIT and 4 or 3) or 0

------------------------------------------------------------- cache model
-- (a, b) pairs with a + b <= NBANK, in a fixed order; state = ab * NCK + k
local AB = {}
for a = 0, NBANK do for b = 0, NBANK - a do AB[#AB + 1] = { a = a, b = b } end end
local NCK = CDEPTH + 1
local ABIX = {}
for i, p in ipairs(AB) do ABIX[p.a .. "," .. p.b] = i - 1 end
local function key(s) return ("a%db%dc%d"):format(s.a, s.b, s.k) end
local function sid(s) return ABIX[s.a .. "," .. s.b] * NCK + s.k end
local HREG, CREG = {}, {}
for i = 0, 3 do HREG[i] = "h" .. i; CREG[i] = "c" .. i end
local SP = { A = "asp", B = "bsp", C = "csp" }
local ISREG = {}
for i = 0, 3 do ISREG[HREG[i]] = true; ISREG[CREG[i]] = true end

local B = {}; B.__index = B
local function builder(s)
  return setmetatable({ s = { a = s.a, b = s.b, k = s.k }, L = {}, n = 0, wr = {},
                        d = { A = 0, B = 0, C = 0 } }, B)
end
function B:copy_state() return { a = self.s.a, b = self.s.b, k = self.s.k } end
function B:line(x) self.L[#self.L + 1] = x end
function B:tmp(e)
  if self.wr[e] then return self.wr[e].v end
  self.n = self.n + 1
  local t = "t" .. self.n
  self:line(("V %s = %s;"):format(t, e))
  return t
end
local function cnt(s, X) return X == "A" and s.a or X == "B" and s.b or s.k end
-- register holding logical depth i of a stack (i < cached count)
local function reg(s, X, i)
  if X == "A" then return HREG[s.a - 1 - i] end
  if X == "B" then return HREG[NBANK - s.b + i] end
  return CREG[s.k - 1 - i]
end
function B:at(X, n)
  local c = cnt(self.s, X)
  if n < c then return reg(self.s, X, n) end
  return ("%s[%d]"):format(SP[X], -(n - c) - 1)
end
function B:top(X) return self:at(X, 0) end
function B:assign(loc, v)
  self:line(("%s = %s;"):format(loc, v))
  if ISREG[loc] then self.wr[loc] = { line = #self.L, v = v } else self.wr[loc] = nil end
end
function B:raw(dst, src) self:line(("%s = %s;"):format(dst, src)); self.wr[dst] = nil end
local function setcnt(s, X, v) if X == "A" then s.a = v elseif X == "B" then s.b = v else s.k = v end end
function B:pop(X)
  self.d[X] = self.d[X] - 1
  local c = cnt(self.s, X)
  if c == 0 then self:line(SP[X] .. "--;"); return end
  local r = reg(self.s, X, 0)
  if self.wr[r] then self.L[self.wr[r].line] = "/* dead write removed */"; self.wr[r] = nil end
  setcnt(self.s, X, c - 1)
end
-- spill the deepest cached cell of X and shift its other cells toward X's anchor
function B:spill_deepest(X)
  local s = self.s
  if X == "A" then
    self:line(("*asp++ = %s;"):format(HREG[0]))
    for i = 0, s.a - 2 do self:raw(HREG[i], HREG[i + 1]) end
    s.a = s.a - 1
  elseif X == "B" then
    self:line(("*bsp++ = %s;"):format(HREG[NBANK - 1]))
    for i = NBANK - 1, NBANK - s.b + 1, -1 do self:raw(HREG[i], HREG[i - 1]) end
    s.b = s.b - 1
  else
    self:line(("*csp++ = %s;"):format(CREG[0]))
    for i = 0, s.k - 2 do self:raw(CREG[i], CREG[i + 1]) end
    s.k = s.k - 1
  end
end
-- v must be a temporary or a constant expression
function B:push(X, v)
  self.d[X] = self.d[X] + 1
  local s = self.s
  if X == "C" then
    if CDEPTH == 0 then self:line(("*csp++ = %s;"):format(v)); return end
    if s.k == CDEPTH then self:spill_deepest("C") end
    self:assign(CREG[s.k], v); s.k = s.k + 1
    return
  end
  if NBANK == 0 then self:line(("*%s++ = %s;"):format(SP[X], v)); return end
  if s.a + s.b == NBANK then                 -- full bank: the pushing stack spills, else the other
    local own = cnt(s, X) > 0 and X or (X == "A" and "B" or "A")
    self:spill_deepest(own)
  end
  if X == "A" then self:assign(HREG[s.a], v); s.a = s.a + 1
  else self:assign(HREG[NBANK - 1 - s.b], v); s.b = s.b + 1 end
end
function B:flush(X)
  local c = cnt(self.s, X)
  for i = c - 1, 0, -1 do self:line(("*%s++ = %s;"):format(SP[X], self:at(X, i))) end
  setcnt(self.s, X, 0)
end
function B:clone()
  local c = builder(self.s); c.n = self.n; c.d = { A = self.d.A, B = self.d.B, C = self.d.C }
  return c
end
function B:next()
  self.fall = self:copy_state(); self.dfall = { self.d.A, self.d.B, self.d.C }
  if JIT then return "[[clang::musttail]] return HOLE_NEXT(PASS);" end
  return ("[[clang::musttail]] return T_%s[*ip](PASS);"):format(key(self.s))
end
function B:taken()
  self.tk = self:copy_state(); self.dtk = { self.d.A, self.d.B, self.d.C }
  if JIT then return "[[clang::musttail]] return HOLE_TAKEN(PASS);" end
  return ("[[clang::musttail]] return T_%s[*ip](PASS);"):format(key(self.s))
end
function B:abort(reason)
  if JIT then return ("{ ((V *)HOLE_FINAL)[3] = %s; return 0; }"):format(reason) end
  return ("{ vm_final.reason = %s; return 0; }"):format(reason)
end

-------------------------------------------------------------- semantics
-- All values are uint64_t cells; signed operations cast to int64_t.
local IMM = {
  PUSH8 = JIT and "(V)(int64_t)(int32_t)(intptr_t)HOLE_IMM" or "(V)(int64_t)(int8_t)ip[1]",
  PUSH32 = JIT and "(V)(int64_t)(int32_t)(intptr_t)HOLE_IMM" or "(V)(int64_t)rd32(ip + 1)",
  PUSH64 = JIT and "((V)(uint32_t)(uintptr_t)HOLE_IMM | (V)(uint32_t)(uintptr_t)HOLE_IMM2 << 32)" or "rd64(ip + 1)",
}
local SEM = {}
local function other(X) return X == "A" and "B" or "A" end

-- binary semantics: f(b, x, y) returns the result expression (may emit checks)
local BIN = {
  ADD = function(b, x, y) return x .. " + " .. y end,
  SUB = function(b, x, y) return x .. " - " .. y end,
  MUL = function(b, x, y) return x .. " * " .. y end,
  AND = function(b, x, y) return x .. " & " .. y end,
  OR  = function(b, x, y) return x .. " | " .. y end,
  XOR = function(b, x, y) return x .. " ^ " .. y end,
  DIVU = function(b, x, y) b:line(("if (%s == 0) %s"):format(y, b:abort(1))); return x .. " / " .. y end,
  REMU = function(b, x, y) b:line(("if (%s == 0) %s"):format(y, b:abort(1))); return x .. " % " .. y end,
  DIVS = function(b, x, y)
    b:line(("if (%s == 0) %s"):format(y, b:abort(1)))
    return ("((int64_t)%s == -1 ? (V)0 - %s : (V)((int64_t)%s / (int64_t)%s))"):format(y, x, x, y)
  end,
  REMS = function(b, x, y)
    b:line(("if (%s == 0) %s"):format(y, b:abort(1)))
    return ("((int64_t)%s == -1 ? (V)0 : (V)((int64_t)%s %% (int64_t)%s))"):format(y, x, y)
  end,
  SHL = function(b, x, y) return ("(%s >= 64 ? (V)0 : %s << %s)"):format(y, x, y) end,
  SHR = function(b, x, y) return ("(%s >= 64 ? (V)0 : %s >> %s)"):format(y, x, y) end,
  SAR = function(b, x, y) return ("(V)((int64_t)%s >> (%s >= 64 ? 63 : %s))"):format(x, y, y) end,
  EQ = function(b, x, y) return ("(V)(%s == %s)"):format(x, y) end,
  NE = function(b, x, y) return ("(V)(%s != %s)"):format(x, y) end,
  LT = function(b, x, y) return ("(V)((int64_t)%s < (int64_t)%s)"):format(x, y) end,
  LE = function(b, x, y) return ("(V)((int64_t)%s <= (int64_t)%s)"):format(x, y) end,
  LTU = function(b, x, y) return ("(V)(%s < %s)"):format(x, y) end,
  LEU = function(b, x, y) return ("(V)(%s <= %s)"):format(x, y) end,
}
local UN = {
  NEG = function(x) return "(V)0 - " .. x end,
  NOT = function(x) return "~" .. x end,
  LNOT = function(x) return x .. " ^ 1" end,
  ZX32 = function(x) return x .. " & 0xffffffffu" end,
  SX32 = function(x) return ("(V)(int64_t)(int32_t)%s"):format(x) end,
  ZX8 = function(x) return x .. " & 0xffu" end,
  ZX16 = function(x) return x .. " & 0xffffu" end,
}
local CHK = {
  CHKU8 = "%s > 0xffu", CHKU16 = "%s > 0xffffu", CHKU32 = "%s > 0xffffffffu",
  CHKI32 = "((int64_t)%s < INT32_MIN || (int64_t)%s > INT32_MAX)",
  CHKNN = "(int64_t)%s < 0",
}

for _, X in ipairs({"A", "B"}) do
  for _, w in ipairs({ "PUSH8", "PUSH32", "PUSH64" }) do
    SEM[w .. "_" .. X] = function(b) b:push(X, b:tmp(IMM[w])) end
  end
  SEM["DUP_" .. X] = function(b) b:push(X, b:tmp(b:top(X))) end
  SEM["DROP_" .. X] = function(b) b:pop(X) end
  SEM["CPUSH_" .. X] = function(b) local t = b:tmp(b:top(X)); b:pop(X); b:push("C", t) end
  SEM["CGET0_" .. X] = function(b) b:push(X, b:tmp(b:at("C", 0))) end
  SEM["CGET1_" .. X] = function(b) b:push(X, b:tmp(b:at("C", 1))) end
  SEM["CSET0_" .. X] = function(b) local t = b:tmp(b:top(X)); b:pop(X); b:raw(b:at("C", 0), t) end
  if JIT then
    -- HOLE_IMM is patched with the final byte offset from csp (cell not cached)
    SEM["CGETN_" .. X] = function(b)
      b:push(X, b:tmp("*(V *)((char *)csp + (intptr_t)(int32_t)(intptr_t)HOLE_IMM)"))
    end
    SEM["CSETN_" .. X] = function(b)
      local t = b:tmp(b:top(X)); b:pop(X)
      b:line(("*(V *)((char *)csp + (intptr_t)(int32_t)(intptr_t)HOLE_IMM) = %s;"):format(t))
    end
  else
    local function slot(b)
      local k = b.s.k
      local e = ("csp[%d - (int)ip[1]]"):format(k - 1)
      for d = k - 1, 0, -1 do e = ("(ip[1] == %d ? %s : %s)"):format(d, CREG[k - 1 - d], e) end
      return e
    end
    SEM["CGETN_" .. X] = function(b) b:push(X, b:tmp(slot(b))) end
    SEM["CSETN_" .. X] = function(b)
      local t = b:tmp(b:top(X)); b:pop(X)
      local k = b.s.k
      local s = ("csp[%d - (int)ip[1]] = %s;"):format(k - 1, t)
      for d = k - 1, 0, -1 do s = ("if (ip[1] == %d) %s = %s; else { %s }"):format(d, CREG[k - 1 - d], t, s) end
      b:line(s)
    end
  end
  SEM["CGETR_" .. X] = function(b)
    b:flush(X); b:flush("C")
    if JIT then
      b:line("{ unsigned dn = (unsigned)(uintptr_t)HOLE_IMM, d = dn & 255u, n = dn >> 8;")
      b:line(("  for (unsigned i = 0; i < n; i++) *%s++ = csp[-1 - (int)d - (int)i]; }"):format(SP[X]))
    else
      b:line(("for (unsigned i = 0; i < ip[2]; i++) *%s++ = csp[-1 - (int)ip[1] - (int)i];"):format(SP[X]))
    end
  end
  -- fixed-depth forms used only by the JIT, which knows the depth when it compiles
  for d = 1, 3 do
    SEM[("CGETD_%s_%d"):format(X, d)] = function(b) b:push(X, b:tmp(b:at("C", d))) end
    SEM[("CSETD_%s_%d"):format(X, d)] = function(b)
      local t = b:tmp(b:top(X)); b:pop(X); b:raw(b:at("C", d), t)
    end
  end
  for name, f in pairs(BIN) do
    SEM[name .. "_" .. X] = function(b)
      local x = b:tmp(b:top("A")); local y = b:tmp(b:top("B"))
      local r = b:tmp(f(b, x, y))
      b:assign(b:top(X), r)
      b:pop(other(X))
    end
  end
  for name, f in pairs(UN) do
    if name ~= "ZX8" and name ~= "ZX16" then
      SEM[name .. "_" .. X] = function(b) local t = b:tmp(b:top(X)); b:assign(b:top(X), b:tmp(f(t))) end
    end
  end
  for _, z in ipairs({ "JZ", "JNZ" }) do
    SEM[z .. "_" .. X] = function(b)
      local t = b:tmp(b:top(X)); b:pop(X)
      local cond = ("%s %s 0"):format(t, z == "JZ" and "==" or "!=")
      if JIT then b:line(("if (%s) { %s }"):format(cond, b:taken())); b:line(b:next())
      else b:line(("{ int16_t off = rd16(ip + 1); ip += 3; if (%s) ip += off; }"):format(cond)) end
      return "done"
    end
  end
end
SEM.ZX8 = function(b) local t = b:tmp(b:top("A")); b:assign(b:top("A"), b:tmp(UN.ZX8(t))) end
SEM.ZX16 = function(b) local t = b:tmp(b:top("A")); b:assign(b:top("A"), b:tmp(UN.ZX16(t))) end
for _, n in ipairs({ "POW", "POWS" }) do
  SEM[n] = function(b)
    local x = b:tmp(b:top("A")); local y = b:tmp(b:top("B"))
    if n == "POWS" then b:line(("if ((int64_t)%s < 0) %s"):format(y, b:abort(4))) end
    b:assign(b:top("A"), b:tmp(("vm_pow(%s, %s)"):format(x, y)))
    b:pop("B")
  end
end
for name, f in pairs(CHK) do
  SEM[name] = function(b)
    local t = b:tmp(b:top("A"))
    b:line(("if (%s) %s"):format(f:format(t, t), b:abort(3)))
  end
end
SEM.COPY_AB = function(b) b:push("B", b:tmp(b:top("A"))) end
SEM.COPY_BA = function(b) b:push("A", b:tmp(b:top("B"))) end
SEM.MOVE_AB = function(b) local t = b:tmp(b:top("A")); b:pop("A"); b:push("B", t) end
SEM.MOVE_BA = function(b) local t = b:tmp(b:top("B")); b:pop("B"); b:push("A", t) end
SEM.CPUSHN = function(b)
  b:flush("A"); b:flush("C")
  if JIT then b:line("for (unsigned i = 0, n = (unsigned)(uintptr_t)HOLE_IMM; i < n; i++) *csp++ = *--asp;")
  else b:line("for (unsigned i = 0; i < ip[1]; i++) *csp++ = *--asp;") end
end
SEM.CPOP = function(b) b:pop("C") end
local CMP = { BEQ = "%s == %s", BNE = "%s != %s", BLT = "(int64_t)%s < (int64_t)%s",
              BLE = "(int64_t)%s <= (int64_t)%s", BLTU = "%s < %s", BLEU = "%s <= %s" }
for name, rel in pairs(CMP) do
  SEM[name] = function(b)
    local x = b:tmp(b:top("A")); local y = b:tmp(b:top("B"))
    b:pop("A"); b:pop("B")
    local cond = rel:format(x, y)
    if JIT then b:line(("if (%s) { %s }"):format(cond, b:taken())); b:line(b:next())
    else b:line(("{ int16_t off = rd16(ip + 1); ip += 3; if (%s) ip += off; }"):format(cond)) end
    return "done"
  end
end
SEM.JMP = function(b)
  if JIT then b:line(b:taken()) else b:line("ip += 3 + rd16(ip + 1);") end
  return "done"
end
SEM.CALL = function(b)
  if JIT then
    b:push("C", b:tmp("(V)(uint32_t)(uintptr_t)HOLE_NEXT"))
    b:line(b:taken())
  else
    b:push("C", b:tmp("(V)(uintptr_t)(ip + 5)"))
    b:line("ip += 5 + rd32(ip + 1);")
  end
  return "done"
end
SEM.TCALL = function(b)
  if JIT then b:line(b:taken()) else b:line("ip += 5 + rd32(ip + 1);") end
  return "done"
end
SEM.RET = function(b)
  local t = b:tmp(b:top("C")); b:pop("C")
  if JIT then
    b.fall = b:copy_state(); b.dfall = { b.d.A, b.d.B, b.d.C }
    b:line(("[[clang::musttail]] return ((H)(uintptr_t)%s)(PASS);"):format(t))
  else
    b:line(("ip = (const uint8_t *)(uintptr_t)%s;"):format(t))
  end
  return "done"
end
-- C at the run-time depth ip[1], as CGETN reads it
local function cslot(b)
  local k = b.s.k
  local e = ("csp[%d - (int)ip[1]]"):format(k - 1)
  for d = k - 1, 0, -1 do e = ("(ip[1] == %d ? %s : %s)"):format(d, CREG[k - 1 - d], e) end
  return e
end
for _, X in ipairs({ "A", "B" }) do
  for _, n in ipairs(OPI_OPS) do
    SEM[n .. "I_" .. X] = function(b)
      local x = b:tmp(b:top(X)); local k = b:tmp(JIT and "(V)(int64_t)(int32_t)(intptr_t)HOLE_IMM" or "(V)(int64_t)(int8_t)ip[1]")
      b:assign(b:top(X), b:tmp(BIN[n](b, x, k)))
    end
  end
  for _, n in ipairs(OPC_OPS) do
    SEM[n .. "C_" .. X] = function(b)
      -- in the JIT the generic form reads C from memory; jit.c turns cached depths into OPCD forms
      local x = b:tmp(b:top(X))
      local c = b:tmp(JIT and "*(V *)((char *)csp + (intptr_t)(int32_t)(intptr_t)HOLE_IMM)" or cslot(b))
      b:assign(b:top(X), b:tmp(BIN[n](b, x, c)))
    end
    for d = 0, 3 do
      SEM[("OPCD_%s_%s_%d"):format(n, X, d)] = function(b)
        local x = b:tmp(b:top(X)); local c = b:tmp(b:at("C", d))
        b:assign(b:top(X), b:tmp(BIN[n](b, x, c)))
      end
    end
  end
end
for name, rel in pairs(CBI) do
  SEM[name] = function(b)
    local x = b:tmp(b:top("A")); b:pop("A")
    local k = b:tmp(JIT and "(V)(int64_t)(int32_t)(intptr_t)HOLE_IMM" or "(V)(int64_t)(int8_t)ip[1]")
    if JIT then b:line(("if (%s) { %s }"):format(rel:format(x, k), b:taken())); b:line(b:next())
    else b:line(("{ int16_t off = rd16(ip + 2); ip += 4; if (%s) ip += off; }"):format(rel:format(x, k))) end
    return "done"
  end
end
-- spec forms quicken themselves, then dispatch again in the same state
local function quicken(check, code) return function(b)
  if JIT then b:line("return 0;"); return "end" end
  b:line(("if (%s) { vm_final.reason = 254; return 0; }"):format(check))
  b:line(("((uint8_t *)ip)[0] = (uint8_t)(%s);"):format(code))
  return "done"
end end
SEM.CALL_A = quicken(("ip[5] > %d"):format(MAXN), "OP_CALL_A_0 + ip[5]")
SEM.CALL_B = quicken(("ip[5] > %d"):format(MAXN), "OP_CALL_B_0 + ip[5]")
SEM.TCALL = quicken(("ip[5] > %d || ip[6] > %d"):format(MAXN, MAXN), ("OP_TCALL_0_0 + ip[5] * %d + ip[6]"):format(MAXN + 1))
SEM.RET = quicken(("ip[1] > %d || ip[2] > %d"):format(MAXN, MAXR), ("OP_RET_0_0 + ip[1] * %d + ip[2]"):format(MAXR + 1))
-- CALL.X: push the return address, recording X in its top bit, then move n argument cells from A into the frame
for _, X in ipairs({ "A", "B" }) do for n = 0, MAXN do
  SEM[("CALL_%s_%d"):format(X, n)] = function(b)
    local ret = JIT and "(V)(uint32_t)(uintptr_t)HOLE_NEXT" or "(V)(uintptr_t)(ip + 6)"
    b:push("C", b:tmp(ret .. (X == "B" and " | ((V)1 << 63)" or "")))
    for _ = 1, n do local t = b:tmp(b:top("A")); b:pop("A"); b:push("C", t) end
    if JIT then b:line(b:taken()) else b:line("ip += 6 + rd32(ip + 1);") end
    return "done"
  end
end end
-- TCALL: drop k frame cells, move n argument cells in, keep the return address
for k = 0, MAXN do for n = 0, MAXN do
  SEM[("TCALL_%d_%d"):format(k, n)] = function(b)
    for _ = 1, k do b:pop("C") end
    for _ = 1, n do local t = b:tmp(b:top("A")); b:pop("A"); b:push("C", t) end
    if JIT then b:line(b:taken()) else b:line("ip += 7 + rd32(ip + 1);") end
    return "done"
  end
end end
-- RET: drop k frame cells, pop the return address; if it records B, move the r results to B in order
for k = 0, MAXN do for r = 0, MAXR do
  SEM[("RET_%d_%d"):format(k, r)] = function(b)
    for _ = 1, k do b:pop("C") end
    local t = b:tmp(b:top("C")); b:pop("C")
    if r > 0 then
      local sub = b:clone()
      local cells = {}
      for i = 0, r - 1 do cells[#cells + 1] = sub:tmp(sub:at("A", i)) end
      for _ = 1, r do sub:pop("A") end
      for i = r, 1, -1 do sub:push("B", cells[i]) end
      if JIT then
        -- a JIT return site expects every cache empty: write the moved results to memory
        for _, X in ipairs({ "A", "B", "C" }) do
          for i = cnt(sub.s, X) - 1, 0, -1 do sub:line(("*%s++ = %s;"):format(SP[X], sub:at(X, i))) end
          setcnt(sub.s, X, 0)
        end
      end
      b.n = sub.n
      b:line(("if (%s >> 63) {"):format(t))
      for _, l in ipairs(sub.L) do b:line("  " .. l) end
      if JIT then b:line(("  [[clang::musttail]] return ((H)(uintptr_t)(%s & 0x7fffffffffffffffull))(PASS);"):format(t))
      else
        b:line(("  ip = (const uint8_t *)(uintptr_t)(%s & 0x7fffffffffffffffull);"):format(t))
        b:line(("  [[clang::musttail]] return T_%s[*ip](PASS);"):format(key(sub.s)))
      end
      b:line("}")
    end
    if JIT then
      b.fall = b:copy_state(); b.dfall = { b.d.A, b.d.B, b.d.C }
      b:line(("[[clang::musttail]] return ((H)(uintptr_t)(%s & 0x7fffffffffffffffull))(PASS);"):format(t))
      return "end"
    end
    b:line(("ip = (const uint8_t *)(uintptr_t)(%s & 0x7fffffffffffffffull);"):format(t))
    return "done"
  end
end end
SEM.ABORT = function(b)
  b:line(b:abort(JIT and "(V)(uint32_t)(uintptr_t)HOLE_IMM" or "ip[1]"))
  return "end"
end
local function imm_u16() return JIT and "(unsigned)(uintptr_t)HOLE_IMM" or "(unsigned)(uint16_t)rd16(ip + 1)" end
local function imm_u32() return JIT and "(uint32_t)(uintptr_t)HOLE_IMM" or "(uint32_t)rd32(ip + 1)" end
local function mem_width(name)
  local w = name:match("32S") and "32S" or name:match("%d+")
  return w == "8" and 1 or w == "16" and 2 or (w == "32" or w == "32S") and 4 or 8, w == "32S" and 1 or 0
end
SEM.HALT = function(b)
  for _, X in ipairs({ "A", "B", "C" }) do
    for i = cnt(b.s, X) - 1, 0, -1 do b:line(("*%s++ = %s;"):format(SP[X], b:at(X, i))) end
  end
  if JIT then b:line("{ V *f = (V *)HOLE_FINAL; f[0] = (V)(uintptr_t)asp; f[1] = (V)(uintptr_t)bsp; f[2] = (V)(uintptr_t)csp; f[3] = 0; }")
  else b:line("vm_final.asp = asp; vm_final.bsp = bsp; vm_final.csp = csp; vm_final.reason = 0;") end
  b:line("return 1;")
  return "end"
end

----------------------------------------------------------------- states
local states = {}
for _, p in ipairs(AB) do for k = 0, CDEPTH do states[#states + 1] = { a = p.a, b = p.b, k = k } end end
local ARGS = "V *asp, V *bsp, V *csp, V h0, V h1, V h2, V h3, V c0, V c1, V c2, V c3"
local PASS = "asp, bsp, csp, h0, h1, h2, h3, c0, c1, c2, c3"
if not JIT then
  -- the interpreter needs ip and one free register for the dispatch jump
  ARGS = "const uint8_t *ip, V *asp, V *bsp, V *csp, V h0, V h1, V h2, V h3, V c0, V c1, V c2"
  PASS = "ip, asp, bsp, csp, h0, h1, h2, h3, c0, c1, c2"
end
local PREAMBLE = ([[
#include <stdint.h>
#include <string.h>
#include "opcodes.h"
typedef uint64_t V;
#define PN __attribute__((preserve_none))
#define ARGS %s
#define PASS %s
typedef PN V (*H)(ARGS);
static inline V vm_pow(V x, V e) { V r = 1; while (e) { if (e & 1) r *= x; x *= x; e >>= 1; } return r; }
 ]]):format(ARGS, PASS)
local out = {}
local function emit(x) out[#out + 1] = x end

if JIT then
  -------------------------------------------------------- JIT stencils
  local JOPS = {}
  for _, p in ipairs(OPS) do JOPS[#JOPS + 1] = p end
  local PSEUDO = {}
  for _, kind in ipairs({ "CGETD", "CSETD" }) do for _, X in ipairs({ "A", "B" }) do for d = 1, 3 do
    local name = ("%s_%s_%d"):format(kind, X, d)
    JOPS[#JOPS + 1] = { name, 1, "n" }
    PSEUDO[#PSEUDO + 1] = { kind = kind, X = X, d = d, id = #JOPS - 1 }
  end end end
  local OPCD = {}
  for i, p in ipairs(OPS) do
    if p[3] == "opc" then
      OPCD[i - 1] = {}
      local n, X = p[1]:match("^(%u+)C_(%u)$")
      for d = 0, 3 do JOPS[#JOPS + 1] = { ("OPCD_%s_%s_%d"):format(n, X, d), 1, "n" }; OPCD[i - 1][d + 1] = #JOPS - 1 end
    end
  end
  local function empty_only(name) return name:match("^CALL_") or name:match("^TCALL") or name:match("^RET") end
  emit("/* generated by gen.lua, mode " .. MODE .. " */")
  emit(PREAMBLE)
  emit("extern PN V HOLE_NEXT(ARGS);\nextern PN V HOLE_TAKEN(ARGS);\nextern char HOLE_IMM[], HOLE_IMM2[], HOLE_FINAL[];")
  local names, FALL, TAKEN, EFF = {}, {}, {}, {}
  for _, s in ipairs(states) do
    for _, p in ipairs(JOPS) do
      local b = builder(s)
      local kind
      if empty_only(p[1]) and (s.a + s.b + s.k > 0) then b:line("return 0;"); kind = "end"
      else kind = SEM[p[1]](b) end
      if kind ~= "done" and kind ~= "end" then b:line(b:next()) end
      local name = ("s_%s_%s"):format(key(s), p[1])
      names[#names + 1] = name
      emit(("PN V %s(ARGS) {"):format(name))
      for _, l in ipairs(b.L) do emit("  " .. l) end
      emit("}")
      FALL[#FALL + 1] = b.fall and sid(b.fall) or 255
      TAKEN[#TAKEN + 1] = b.tk and sid(b.tk) or 255
      if s.a == 0 and s.b == 0 and s.k == 0 then EFF[#EFF + 1] = { b.dfall or { 0, 0, 0 }, b.dtk or { 0, 0, 0 } } end
    end
  end
  -- conform stencils: operand bank (a,b) -> (a2,b2), and C k -> k2
  local function conform_stack(b, X, to)
    local s = b.s
    local c = cnt(s, X)
    local vals = {}
    for i = 0, c - 1 do vals[#vals + 1] = b:tmp(b:at(X, i)) end
    while #vals > to do b:line(("*%s++ = %s;"):format(SP[X], table.remove(vals))) end
    while #vals < to do vals[#vals + 1] = b:tmp("*--" .. SP[X]) end
    return vals
  end
  for _, f in ipairs(AB) do for _, t in ipairs(AB) do
    local b = builder({ a = f.a, b = f.b, k = 0 })
    local va = conform_stack(b, "A", t.a)
    local vb = conform_stack(b, "B", t.b)
    b.s.a, b.s.b = t.a, t.b
    for i = 0, t.a - 1 do b:raw(b:at("A", i), va[i + 1]) end
    for i = 0, t.b - 1 do b:raw(b:at("B", i), vb[i + 1]) end
    local name = ("k_ab_%d%d_%d%d"):format(f.a, f.b, t.a, t.b)
    names[#names + 1] = name
    emit(("PN V %s(ARGS) {"):format(name))
    for _, l in ipairs(b.L) do emit("  " .. l) end
    emit("  [[clang::musttail]] return HOLE_NEXT(PASS);\n}")
  end end
  for kf = 0, CDEPTH do for kt = 0, CDEPTH do
    local b = builder({ a = 0, b = 0, k = kf })
    local vc = conform_stack(b, "C", kt)
    b.s.k = kt
    for i = 0, kt - 1 do b:raw(b:at("C", i), vc[i + 1]) end
    local name = ("k_c_%d_%d"):format(kf, kt)
    names[#names + 1] = name
    emit(("PN V %s(ARGS) {"):format(name))
    for _, l in ipairs(b.L) do emit("  " .. l) end
    emit("  [[clang::musttail]] return HOLE_NEXT(PASS);\n}")
  end end
  local f = assert(io.open(OUT, "w")); f:write(table.concat(out, "\n"), "\n"); f:close()

  local base = OUT:gsub("%.c$", "")
  local of = assert(io.open(base .. "_order.txt", "w")); of:write(table.concat(names, "\n"), "\n"); of:close()
  local M = { "/* generated by gen.lua, mode " .. MODE .. " */" }
  M[#M + 1] = ("#define NSTATE %d\n#define NAB %d\n#define NCK %d\n#define NOPS %d\n#define NBANK %d")
    :format(#states, #AB, NCK, #JOPS, NBANK)
  M[#M + 1] = "#define PN __attribute__((preserve_none))"
  M[#M + 1] = "typedef PN uint64_t (*H)(uint64_t *, uint64_t *, uint64_t *" .. string.rep(", uint64_t", 8) .. ");"
  M[#M + 1] = "#define JIT_ENTER(f, a, b, c) ((H)(f))(a, b, c" .. string.rep(", 0", 8) .. ")"
  local aa, bb = {}, {}
  for _, p in ipairs(AB) do aa[#aa + 1] = p.a; bb[#bb + 1] = p.b end
  M[#M + 1] = "static const unsigned char ab_a[] = {" .. table.concat(aa, ",") .. "};"
  M[#M + 1] = "static const unsigned char ab_b[] = {" .. table.concat(bb, ",") .. "};"
  local ix = {}
  for a = 0, 4 do local row = {} for b = 0, 4 do row[#row + 1] = ABIX[a .. "," .. b] or 255 end ix[#ix + 1] = "{" .. table.concat(row, ",") .. "}" end
  M[#M + 1] = "static const unsigned char ab_index[5][5] = {" .. table.concat(ix, ",") .. "};"
  local function rows(T)
    local r = {}
    for i = 0, #states - 1 do
      local row = {}
      for j = 1, #JOPS do row[#row + 1] = T[i * #JOPS + j] end
      r[#r + 1] = "  {" .. table.concat(row, ",") .. "}"
    end
    return table.concat(r, ",\n")
  end
  M[#M + 1] = ("static const unsigned char st_fall[%d][NOPS] = {\n%s\n};"):format(#states, rows(FALL))
  M[#M + 1] = ("static const unsigned char st_taken[%d][NOPS] = {\n%s\n};"):format(#states, rows(TAKEN))
  local ef, et = {}, {}
  for _, e in ipairs(EFF) do
    ef[#ef + 1] = ("{%d,%d,%d}"):format(e[1][1], e[1][2], e[1][3])
    et[#et + 1] = ("{%d,%d,%d}"):format(e[2][1], e[2][2], e[2][3])
  end
  M[#M + 1] = "static const signed char eff_fall[NOPS][3] = {" .. table.concat(ef, ",") .. "};"
  M[#M + 1] = "static const signed char eff_taken[NOPS][3] = {" .. table.concat(et, ",") .. "};"
  local function pmap(kind)
    local r = {}
    for _, X in ipairs({ "A", "B" }) do
      local row = { 0, 0, 0, 0 }
      for _, p in ipairs(PSEUDO) do if p.kind == kind and p.X == X then row[p.d + 1] = p.id end end
      r[#r + 1] = "{" .. table.concat(row, ",") .. "}"
    end
    return table.concat(r, ",")
  end
  M[#M + 1] = "static const unsigned short cgetd_op[2][4] = {" .. pmap("CGETD") .. "};"
  local oc = {}
  for i = 0, #OPS - 1 do local v = OPCD[i] or { 0, 0, 0, 0 }; oc[#oc + 1] = "{" .. table.concat(v, ",") .. "}" end
  M[#M + 1] = "static const unsigned short opcd_op[][4] = {" .. table.concat(oc, ",") .. "};"
  M[#M + 1] = "static const unsigned short csetd_op[2][4] = {" .. pmap("CSETD") .. "};"
  local mf = assert(io.open(base .. "_meta.h", "w")); mf:write(table.concat(M, "\n"), "\n"); mf:close()
  io.stderr:write(("%s: %d states, %d stencils\n"):format(OUT, #states, #names))
  return
end

--------------------------------------------------------- interpreter
emit("/* generated by gen.lua, mode " .. MODE .. " */")
emit(PREAMBLE)
emit([[
static inline int16_t rd16(const uint8_t *p) { int16_t v; memcpy(&v, p, 2); return v; }
static inline int32_t rd32(const uint8_t *p) { int32_t v; memcpy(&v, p, 4); return v; }
static inline V rd64(const uint8_t *p) { V v; memcpy(&v, p, 8); return v; }
struct vm_final { V *asp, *bsp, *csp; V reason; } vm_final;
static PN V bad(ARGS) { vm_final.reason = 255; return 0; }]])
for _, s in ipairs(states) do for _, p in ipairs(OPS) do emit(("static PN V h_%s_%s(ARGS);"):format(key(s), p[1])) end end
for _, s in ipairs(states) do
  local e = { "[0 ... 255] = bad" }
  for _, p in ipairs(OPS) do e[#e + 1] = ("[OP_%s] = h_%s_%s"):format(p[1], key(s), p[1]) end
  emit(("static const H T_%s[256] = { %s };"):format(key(s), table.concat(e, ", ")))
end
local nh = 0
-- handlers that rarely run are marked cold, so the compiler moves them out of the hot code
local function is_cold(name)
  return name == "HALT" or name == "ABORT" or name:match("^CHK") or name:match("^DIV") or name:match("^REM")
      or name:match("^POW") or name == "CALL_A" or name == "CALL_B" or name == "TCALL" or name == "RET"
end
-- emitted grouped by opcode, so one instruction's handlers for all cache states sit together
for _, s in ipairs(states) do
  for _, p in ipairs(OPS) do
    local b = builder(s)
    local kind = SEM[p[1]](b)
    emit(("static PN %sV h_%s_%s(ARGS) {"):format(is_cold(p[1]) and "__attribute__((cold)) " or "", key(s), p[1]))
    for _, l in ipairs(b.L) do emit("  " .. l) end
    if kind ~= "done" and kind ~= "end" then emit(("  ip += %d;"):format(p[2])) end
    if kind ~= "end" then emit("  " .. b:next()) end
    emit("}")
    nh = nh + 1
  end
end
emit(([[
V vm_run(const uint8_t *code, V *as, V *bs, V *cs) {
  vm_final.reason = 0;
  return T_%s[*code](code, as, bs, cs, 0, 0, 0, 0, 0, 0, 0);
}]]):format(key({ a = 0, b = 0, k = 0 })))
local f = assert(io.open(OUT, "w")); f:write(table.concat(out, "\n"), "\n"); f:close()
io.stderr:write(("%s: %d states, %d handlers\n"):format(OUT, #states, nh))
