-- luajit bundle.lua [output]        (default: dist/let.lua)
--
-- Writes one Lua file carrying the compiler and everything it requires, so the compiler can be used
-- without the checkout: `luajit dist/let.lua program.let -o program.c`.
--
-- THE MODULE SET IS DISCOVERED, NOT LISTED. Start at the entry point, read the `require` calls in each
-- source, follow them. A hand-kept list is a second place that knows what the compiler is made of, and
-- the failure it produces is the worst kind: the bundle keeps building, every test inside the tree keeps
-- passing -- because the tree is still on `package.path` -- and the missing module shows up only when
-- somebody runs the bundle.
--
-- The output is host-independent. The compiler uses nothing but the standard library, so unlike the
-- legacy bundle there are no host-specific backends to carry as text; it parses and runs on LuaJIT and
-- on PUC Lua 5.3+, and either host writes byte-identical output. A module that the HOST provides is not
-- carried: the bundle's `require` falls back to the real one.
package.path = './?.lua;./?/init.lua;' .. package.path

local output = arg[1] or 'dist/let.lua'
local ENTRY = 'let'

-- What the runtime provides, so it is not carried and not looked for.
local EXTERNAL = {}
for _, name in ipairs{ 'ffi', 'bit', 'jit', 'debug', 'io', 'os', 'math', 'string', 'table',
                       'coroutine', 'package', 'utf8' } do
    EXTERNAL[name] = true
end

-- The two spellings `package.path` looks for: a file, or a package directory.
local function source_of(name)
    local stem = name:gsub('%.', '/')
    for _, path in ipairs{ stem .. '.lua', stem .. '/init.lua' } do
        local file = io.open(path, 'rb')
        if file then
            local text = file:read('*a')
            file:close()
            return text, path
        end
    end
    return nil, stem .. '.lua'
end

-- Depth-first from the entry point, keeping the order each module was first reached. The order is the
-- order they are written in, which is also a valid dependency order because a module is collected
-- before the modules IT requires.
local modules, seen, order = {}, {}, {}
local function collect(name)
    if seen[name] or EXTERNAL[name] then return end
    seen[name] = true
    local text, path = source_of(name)
    assert(text, ("bundle: cannot find module '%s' (looked for %s)"):format(name, path))
    modules[name] = { text = text, path = path }
    order[#order + 1] = name
    -- Either quote style, and both spellings of a call: `require('x')` and `require 'x'`. Missing one
    -- leaves a module out while everything inside the tree still passes.
    for required in text:gmatch([[require%s*%(?%s*['"]([^'"]+)['"]%s*%)?]]) do collect(required) end
    for required in text:gmatch([[require%s*['"]([^'"]+)['"]%s*%(]]) do collect(required) end
end
collect(ENTRY)
-- The command line is reached from the generated script rather than from `let`, so it is collected
-- explicitly -- nothing requires it.
collect('let.cli')

local out = {}
local function line(text) out[#out + 1] = text end
line('-- Generated by bundle.lua from ' .. #order .. ' modules. Do not edit.')
line('--')
line('-- The Let compiler in one file: no installation, no package.path, and no dependency beyond the')
line('-- host it runs on. Requiring it returns what the module layout returns (the vocabulary table);')
line('-- running it as a script compiles a file, with the exit codes `letc` documents.')
line('local bundled, loaded = {}, {}')
line('local host_require = require')
line('-- A bundled chunk is called with its own name, as a Lua module chunk is, and whatever it returns')
line('-- is what `require` gives back -- so the bundle behaves exactly like the tree it was built from.')
line('local function require(name)')
line('    local value = loaded[name]')
line('    if value ~= nil then return value end')
line('    local chunk = bundled[name]')
line('    if not chunk then return host_require(name) end')
line('    value = chunk(require, name)')
line('    if value == nil then value = package.loaded[name] end')
line('    if value == nil then value = true end')
line('    loaded[name] = value')
line('    return value')
line('end')
line('local function module(name, chunk) bundled[name] = chunk end')
for _, name in ipairs(order) do
    line('')
    line(('-- %s'):format(modules[name].path))
    line(("module('%s', function(require, ...)"):format(name))
    line(modules[name].text)
    line('end)')
end
line('')
line("local V = require('let')")
line('-- Run as a script rather than required: compile what the command line names. The test is whether')
line('-- this chunk IS the running script, so loading it into another program is not mistaken for it.')
line("local source, script = debug.getinfo(1, 'S').short_src, arg and arg[0]")
line('if script and source == script then')
line("    os.exit(require('let.cli')(V)(arg))")
line('else')
line('    return V')
line('end')

local directory = output:match('^(.*)/[^/]+$')
if directory then os.execute('mkdir -p ' .. directory) end
local handle = assert(io.open(output, 'wb'))
handle:write(table.concat(out, '\n') .. '\n')
handle:close()
print(('wrote %s: %d modules, %d lines'):format(output, #order, #out))
