-- luajit bundle.lua [output]
--
-- Writes one Lua file containing the compiler and everything it requires. Every module here is a
-- chunk that returns its value, so bundling is a registry and a function wrapper: the bundle
-- defines each module under its own name and hands every one of them a `require` that resolves
-- from the registry, falling back to LuaJIT's own for anything not bundled (`ffi`, in scalar).
--
-- The module set is discovered rather than listed: start at the entry point, read the `require`
-- calls in each source, and pull in whatever is found. A module added later cannot be forgotten.
package.path = './?.lua;./?/init.lua;' .. package.path

local output = arg[1] or 'dist/let.lua'
local entry = 'let'
-- Names the bundle does not carry because the runtime provides them.
local external = {}
for _, name in ipairs{'ffi','bit','jit','debug','io','os','math','string','table','coroutine','package'} do
    external[name] = true
end

local function source_of(name)
    -- The same two spellings `package.path` looks for: a file, or a package directory.
    local stem = name:gsub('%.', '/')
    for _, path in ipairs{stem .. '.lua', stem .. '/init.lua'} do
        local file = io.open(path, 'rb')
        if file then
            local text = file:read('*a')
            file:close()
            return text, path
        end
    end
    return nil, stem .. '.lua'
end

-- Depth-first from the entry point, keeping the order each module was first reached.
local modules, seen, order = {}, {}, {}
local function collect(name)
    if seen[name] then return end
    if external[name] then return end
    seen[name] = true
    local text, path = source_of(name)
    assert(text, ("bundle: cannot find module '%s' (%s)"):format(name, path))
    modules[name] = {text = text, path = path}
    order[#order + 1] = name
    -- Either quote style: the vendored files use double quotes, and missing one leaves a module
    -- out of the bundle while every test inside the repository still passes, because the tree is
    -- still on package.path here.
    for required in text:gmatch([[require%s*%(?%s*['"]([^'"]+)['"]%s*%)?]]) do collect(required) end
    for required in text:gmatch([[require%s*['"]([^'"]+)['"]%s*%(]]) do collect(required) end
end
collect(entry)

local out = {}
local function line(text) out[#out + 1] = text end
line('-- Generated by bundle.lua from ' .. #order .. ' modules. Do not edit.')
line('--')
line('-- The Let compiler in one file: no installation, no package.path, no dependencies beyond the')
line('-- LuaJIT runtime it uses for 64-bit arithmetic. Requiring it returns the same table the')
line('-- module layout returns; running it as a script compiles a file.')
line('local bundled, loaded = {}, {}')
line('local requires = require')
line('-- A bundled chunk is called with its own name, as a Lua module chunk is, because the')
line('-- vendored files register themselves in package.loaded rather than returning a value.')
line('local function require(name)')
line('    local value = loaded[name]')
line('    if value ~= nil then return value end')
line('    local chunk = bundled[name]')
line('    if not chunk then return requires(name) end')
line('    value = chunk(require, name)')
line('    if value == nil then value = package.loaded[name] end')
line('    if value == nil then value = true end')
line('    loaded[name] = value')
line('    return value')
line('end')
line('local function module(name, chunk) bundled[name] = chunk end')
for _, name in ipairs(order) do
    line('')
    line(('-- %s'):format(modules[name].path))
    line(("module('%s', function(require, ...)"):format(name))
    line(modules[name].text)
    line('end)')
end
line('')
line("local V = require('let')")
line('-- Run as a script rather than required: compile arg[1] to arg[2], or to stdout.')
line("local this, script = debug.getinfo(1, 'S').short_src, arg and arg[0]")
line('-- Run as a script rather than required: compile arg[1] to arg[2], or to stdout. The test is')
line('-- whether this chunk *is* the running script; loading it into another program is not.')
line('if script and this == script and arg[1] then')
line("    local options = arg[3] and dofile(arg[3]) or {}")
line("    local file = assert(io.open(arg[1], 'rb'))")
line("    local text = file:read('*a'); file:close()")
line('    local program, builder = V.parse(text, arg[1]):build(options)')
line('    -- This is a host, and it publishes every exported word.')
line('    options.entries = options.entries or builder.host_entries')
line('    program:verify_flow(options.hosts or {})')
line('    local source = V.print(program:emit(options))')
line('    if arg[2] then')
line("        local handle = assert(io.open(arg[2], 'wb')); handle:write(source); handle:close()")
line('    else io.write(source) end')
line('elseif script and this == script then')
line('    io.stderr:write("usage: luajit let.lua input.let [output.c [options.lua]]\\n")')
line('    os.exit(1)')
line('else')
line('    return V')
line('end')

local directory = output:match('^(.*)/[^/]+$')
if directory then os.execute('mkdir -p ' .. directory) end
local handle = assert(io.open(output, 'wb'))
handle:write(table.concat(out, '\n') .. '\n')
handle:close()
print(('wrote %s: %d modules, %d lines'):format(output, #order, #out))
