-- luajit new/bundle.lua [output]        (default: dist/word.lua)
--
-- Build the Lua Word compiler as one deterministic LuaJIT file. Source lookup is
-- rooted beside this script, not in the caller's working directory. The generated
-- file can be run like wordc.lua or required to obtain the Word embedding API.
local source = debug.getinfo(1, "S").source
local script = source:sub(1, 1) == "@" and source:sub(2) or source
local root = script:match("^(.*[/])") or "./"
local output = arg[1] or "dist/word.lua"

-- These modules are supplied by LuaJIT. They must remain real host modules: in
-- particular word.host inspects VM bytecode through jit.util and clones terminals
-- with string.dump/loadstring while preserving their host function environments.
local external = {}
for _, name in ipairs({
    "bit", "jit", "jit.util", "ffi", "debug", "io", "math", "os", "package",
    "string", "table", "coroutine",
}) do external[name] = true end

local function read(path)
    local file = io.open(path, "rb")
    if not file then return nil end
    local text = file:read("*a")
    file:close()
    return text
end

local function source_of(name)
    local stem = name:gsub("%.", "/")
    for _, relative in ipairs({ stem .. ".lua", stem .. "/init.lua" }) do
        local text = read(root .. relative)
        if text then return text, relative end
    end
    return nil, stem .. ".lua or " .. stem .. "/init.lua"
end

-- Return literal requires in source order. Supporting both call spellings and
-- quote styles keeps discovery independent of formatting. Nonliteral host loads
-- intentionally remain runtime require calls.
local require_patterns = {
    'require%s*%(%s*"([^"]+)"%s*%)',
    "require%s*%(%s*'([^']+)'%s*%)",
    'require%s*"([^"]+)"',
    "require%s*'([^']+)'",
}
local function literal_requires(text)
    local found, cursor = {}, 1
    while true do
        local first_start, first_end, first_name
        for _, pattern in ipairs(require_patterns) do
            local at, finish, name = text:find(pattern, cursor)
            if at and (not first_start or at < first_start or (at == first_start and finish > first_end)) then
                first_start, first_end, first_name = at, finish, name
            end
        end
        if not first_start then return found end
        found[#found + 1] = first_name
        cursor = first_end + 1
    end
end

local modules, order, seen = {}, {}, {}
local function collect(name)
    if seen[name] or external[name] then return end
    seen[name] = true
    local text, looked = source_of(name)
    assert(text, ("bundle: cannot find module '%s' beside %s (looked for %s)")
        :format(name, script, looked))
    modules[name] = { text = text, path = looked }
    order[#order + 1] = name
    for _, dependency in ipairs(literal_requires(text)) do collect(dependency) end
end

-- `word.cli` is a second entry point: the embedding API does not depend on its
-- launcher, but a generated file does. Everything below these roots is discovered.
collect("word")
collect("word.cli")

local out = {}
local function line(text) out[#out + 1] = text end
line("-- Generated by new/bundle.lua from " .. #order .. " modules. Do not edit.")
line("-- Run this file like new/wordc.lua, or require it to obtain the Word API.")
line("local bundled, loaded, loading = {}, {}, {}")
line("local host_require = require")
line("local function require(name)")
line("    local value = loaded[name]")
line("    if value then return value end")
line("    local chunk = bundled[name]")
line("    if not chunk then return host_require(name) end")
line("    if loading[name] then error('loop loading bundled module ' .. name, 0) end")
line("    loading[name] = true")
line("    local ok")
line("    ok, value = pcall(chunk, require, name)")
line("    loading[name] = nil")
line("    if not ok then error(value, 0) end")
line("    if value == nil then value = package.loaded[name] end")
line("    if value == nil then value = true end")
line("    loaded[name] = value")
line("    return value")
line("end")
line("local function module(name, chunk) bundled[name] = chunk end")
for _, name in ipairs(order) do
    line("")
    line("-- " .. modules[name].path)
    line(("module(%q, function(require, ...)"):format(name))
    line(modules[name].text)
    line("end)")
end
line("")
line("local Word = require('word')")
line("local source = debug.getinfo(1, 'S').source")
line("local script = source:sub(1, 1) == '@' and source:sub(2) or source")
line("if arg and arg[0] == script then")
line("    os.exit(require('word.cli')(Word, arg))")
line("end")
line("return Word")

local function shell_quote(value) return "'" .. value:gsub("'", "'\\''") .. "'" end
local directory = output:match("^(.*)/[^/]*$")
if directory ~= nil then
    if directory == "" then directory = "/" end
    local status = os.execute("mkdir -p -- " .. shell_quote(directory))
    assert(status == true or status == 0, "bundle: cannot create output directory " .. directory)
end
local handle, err = io.open(output, "wb")
assert(handle, "bundle: cannot write " .. output .. ": " .. tostring(err))
assert(handle:write(table.concat(out, "\n"), "\n"))
assert(handle:close())
print(("wrote %s: %d modules, %d lines"):format(output, #order, #out))
