local H = ...
local Word = require("word")
local Model = require("word.model")

H.test("primitive specialization is lazy, canonical and shares its constructor definition", function()
    local s = Word.new(); local three = s.U32:of(3)
    H.eq(three, s.U32:of(s.U32(3))); H.eq(three, s.U32:of(3.0))
    H.eq(three:of(), three); H.eq(s.U32:of(), s.U32)
    H.eq(Model.word(three).definition, Model.word(s.U32).definition)
    H.eq(Model.primitive(three), nil); H.eq(Model.primitive(s.U32), "U32")
    H.eq(Model.word(three).result, nil)
    H.eq(s:value(three()), 3); H.eq(Model.word(three).result, nil)
    local value = s:normalize(three)
    H.eq(value, s:normalize(three)); H.eq(s:value(value), 3)
    H.eq(s:value(three + 4), 7); H.eq(three:eq(3), true)
    H.eq(s:value(s.U32(4)), 4); H.eq(s:type(s.U32), s.U32)
end)

H.test("Bool false bindings survive and Unit empty specialization is an identity", function()
    local s = Word.new()
    local no, yes = s.Bool:of(false), s.Bool:of(true)
    assert(no ~= yes); H.eq(no, s.Bool:of(s.Bool(false)))
    H.eq(s:value(no()), false); H.eq(s:value(yes()), true)
    H.eq(s:value(no), false); H.eq(s:value(yes), true)
    H.eq(s.Unit:of(), s.Unit); H.eq(s:normalize(s.Unit:of()), s.Unit)
    H.eq(s:value(s.Unit:of()()), nil)
    H.raises("reject", "arity", function() s.Unit:of(nil) end)
    H.raises("reject", "arity", function() s.Unit:of{} end)
end)

H.test("Type specialization follows single-call and nonempty forwarding rules", function()
    local s = Word.new(); local T = s.Type:of(s.U32)
    H.eq(T(), s.U32); H.eq(s:normalize(T), s.U32); H.eq(s:type(T), s.U32)
    H.eq(s:value(T(9)), 9); H.eq(T:of(9), s.U32:of(9))
    H.eq(s.Type:of(s.Type):of(s.U32), T)
    H.eq(s.Type:of(s.Type)(), s.Type); H.eq(s:type(s.Type:of(s.Type)), s.Type)
    local unit = s.Type:of(s.Unit)
    H.eq(unit(), s.Unit); H.eq(s:value(unit()()), nil)
    H.raises("reject", "arity", function() unit(1) end)
    H.raises("reject", "arity", function() unit:of(1) end)
end)

H.test("Type constructor aliases work in signatures, fields and keyed factory forwarding", function()
    local s = Word.new(); local T = s.Type:of(s.U32)
    local P = s.word{x = T}; local Alias = s.Type:of(P)
    H.eq(s:type(Alias), s:type(P)); H.eq(Alias.x, s.U32)
    H.eq(s:value(Alias{x = 7}.x), 7)
    local Fixed = Alias:of{x = 8}
    H.eq(s:value(Fixed{}.x), 8)
    local f = s.word(T, function(x) return x + 1 end)
    H.eq(s:value(f(3)), 4)
    H.eq(s:compile{functions = {f = f}}.functions[1].parameters[1].type, s.U32)
end)

H.test("specialized primitive values are not accepted as data type requirements", function()
    local s = Word.new(); local three = s.U32:of(3)
    H.raises("reject", "type-required", function() s:type(three) end)
    H.raises("reject", "type-required", function() s.Type(three) end)
    H.raises("reject", "type-required", function() s.Type:of(three) end)
    local C = s.word{x = three}; H.eq(s:value(C{}.x()), 3) -- A closed executable child, not a data slot.
    local f = s.word(three, function(x) return x end)
    H.raises("reject", "type-required", function() f(3) end)
    H.raises("reject", "type-required", function() s:compile{functions = {f = f}} end)
    H.raises("reject", "type-required", function() s:compile{types = {bad = three}} end)
    H.raises("reject", "export-word", function() s:compile{functions = {bad = s.Type:of(s.U32)}} end)
end)

H.test("primitive callback requirements use the remaining constructor inputs", function()
    local s = Word.new()
    local zero = s.word(s.word(), function(f) return f() end)
    local unary = s.word(s.word(s.U32), s.U32, function(f, x) return f(x) end)
    H.eq(s:value(zero:of(s.U32:of(7))()), 7)
    H.eq(s:value(zero(s.Bool:of(false))), false)
    H.eq(s:value(zero(s.Unit)), nil)
    H.eq(s:value(unary:of(s.Type:of(s.U32))(8)), 8)
    local using_type = s.word(s.word(), s.U32, function(f, x) return f()(x) end)
    H.eq(s:value(using_type:of(s.Type:of(s.U32))(9)), 9)
    H.raises("reject", "callable-shape", function() zero:of(s.U32) end)
    H.raises("reject", "callable-required", function() unary:of(s.U32:of(3)) end)
    H.eq(Model.word(s.U32:of(7)).result, nil) -- Neither binding nor ordinary execution memoizes it.
    s:compile{functions = {constant = zero:of(s.U32:of(7))}}
    H.eq(s:value(Model.word(s.U32:of(7)).result), 7) -- Static demand does.
end)

H.test("primitive static arguments keep literal, arity and session checks", function()
    local s = Word.new(); local other = Word.new()
    for _, bad in ipairs({-1, 0x100000000, 0.5, true, "3", {}}) do
        H.raises("reject", "type", function() s.U32:of(bad) end)
    end
    H.raises("reject", "type", function() s.U32:of(nil) end)
    H.raises("reject", "type", function() s.Bool:of(1) end)
    H.raises("reject", "type-required", function() s.Type:of(nil) end)
    H.raises("reject", "arity", function() s.U32:of(1, 2) end)
    H.raises("reject", "arity", function() s.U32:of(1):of(1) end)
    H.raises("reject", "arity", function() s.U32:of(1)(1) end)
    H.raises("reject", "foreign-session", function() s.U32:of(other.U32(1)) end)
    H.raises("reject", "foreign-session", function() s.Type:of(other.U32) end)
end)

H.test("primitive static supply rejects symbols and executable results retain their boundary", function()
    local s = Word.new(); local m = s:load_string([[
        return {symbol = word(U32, function(x) return U32:of(x)() end),
            escape = word(U32, function(x) return U32:of(3) end)}
    ]])
    H.raises("reject", "static-required", function() s:compile{functions = {f = m.symbol}} end)
    assert(require("word.ir").verify(s:compile{functions = {f = m.escape}}))
    H.eq(s:value(m.symbol(4)), 4)
    H.eq(s._engine.scope:current(), nil)
end)

H.test("computed primitive supply leaves the receiving terminal lazy", function()
    local s = Word.new(); local U32 = s.U32
    local value = s.word(function()
        local n = 0; for _ = 1, 10000 do n = n + 1 end
        return U32(n)
    end)
    local bound = s.U32:of(value)
    H.eq(Model.word(bound).result, nil)
    H.eq(s:value(bound()), 10000)
end)
