local IR = require("word.ir")
local D = require("word.diagnostic")
local table = require("word.host").table
local Model = require("word.model")
local M = {}

local function escape(name)
    return name:gsub("[^A-Za-z0-9]", function(c) return string.format("_%02x", c:byte()) end)
end
function M.name(name) return "word_" .. escape(name) end
function M.type_name(name) return "wordtype_" .. escape(name) end
function M.result_type_name(name) return "wordresult_" .. escape(name) end
function M.field_name(name) return "f_" .. escape(name) end
local function v(id) return "v" .. id end
local function literal(t, value)
    if Model.primitive(t) == "Bool" then return value and "true" or "false" end
    return "UINT32_C(" .. tostring(value) .. ")"
end

function M.emit(program)
    IR.verify(program)
    local names, order, sizes, serial = {}, {}, {}, 0
    local function ctype(t)
        local primitive = Model.primitive(t)
        if primitive then return assert(({ U32 = "uint32_t", Bool = "bool", Unit = "void" })[primitive]) end
        if not names[t] then
            serial = serial + 1
            local abi = Model.callable(t)
            names[t] = (abi and (abi.code and "wordclosure_" or "wordcallable_") or "wordrecord_") .. serial
            if abi then
                ctype(abi.result)
                if abi.environment then ctype(abi.environment) end
                for _, p in ipairs(abi.parameters) do ctype(p.type) end
                sizes[t] = 2; order[#order + 1] = t
                return names[t]
            end
            local def = assert(Model.record(t))
            local size = 0
            for _, field in ipairs(def.runtime_order) do
                local ft = def.fields[field]; ctype(ft)
                size = size + (sizes[ft] or (Model.primitive(ft) == "Unit" and 0 or 1))
                if size > 65536 then D.resource("record-layout", "C record layout exceeds 65536 scalar/empty slots") end
            end
            sizes[t] = math.max(1, size)
            order[#order + 1] = t -- By-value children precede their containing structs.
        end
        return names[t]
    end
    for _, export in ipairs(program.types or {}) do ctype(export.type) end
    for _, fn in ipairs(program.functions) do
        ctype(fn.result)
        if fn.receiver then ctype(fn.receiver.type) end
        if fn.captures then ctype(fn.captures.type) end
        for _, p in ipairs(fn.parameters) do ctype(p.type) end
        for _, block in ipairs(fn.blocks) do
            for _, ins in ipairs(block.instructions) do ctype(ins.type) end
        end
    end
    local borrowing_calls = require("word.borrow").verify(program)
    local out = { "/* Generated by the Lua Word DSL. */", "#include <stdint.h>", "#include <stdbool.h>", "#include <stdlib.h>", "" }
    for _, t in ipairs(order) do
        local abi = Model.callable(t)
        if abi and abi.code then
            out[#out + 1] = "typedef struct { " ..
                (abi.environment and (ctype(abi.environment) .. (abi.value_environment and " environment;" or " *environment;")) or "unsigned char word_empty;") ..
                " } " .. ctype(t) .. ";"
        elseif abi then
            local parameters = {"void *"}
            for _, p in ipairs(abi.parameters) do parameters[#parameters + 1] = ctype(p.type) end
            out[#out + 1] = "typedef struct { " .. ctype(abi.result) .. " (*invoke)(" ..
                table.concat(parameters, ", ") .. "); void *environment; } " .. ctype(t) .. ";"
        else
        local def, count = Model.record(t), 0
        out[#out + 1] = "typedef struct {"
        for _, name in ipairs(def.runtime_order) do
            local ft = def.fields[name]
            if Model.primitive(ft) ~= "Unit" then
                out[#out + 1] = "    " .. ctype(ft) .. " " .. M.field_name(name) .. ";"; count = count + 1
            end
        end
        if count == 0 then out[#out + 1] = "    unsigned char word_empty;" end
        out[#out + 1] = "} " .. ctype(t) .. ";"
        end
    end
    for _, export in ipairs(program.types or {}) do
        out[#out + 1] = "typedef " .. ctype(export.type) .. " " .. M.type_name(export.name) .. ";"
    end
    out[#out + 1] = ""
    for _, export in ipairs(program.exports) do
        local t = program.functions[export.target].result
        if Model.callable(t) or (Model.record(t) and Model.record(t).tuple_arity) then
            out[#out + 1] = "typedef " .. ctype(t) .. " " .. M.result_type_name(export.name) .. ";"
        end
    end
    local function target(ins, fn)
        if ins.closure then return "(" .. (ins.by_value and "" or "*") .. v(ins.closure) .. ".environment)" end
        local path = fn.receiver and ins.root == fn.receiver.id and ("(*" .. v(ins.root) .. ")") or v(ins.root)
        for _, name in ipairs(ins.path) do path = path .. "." .. M.field_name(name) end
        return path
    end
    local function_names, reachable, definitions = {}, {}, {}
    local function visit(id)
        if reachable[id] then return end
        reachable[id] = true
        for _, block in ipairs(program.functions[id].blocks) do
            for _, ins in ipairs(block.instructions) do
                if (ins.op == "Call" and ins.target ~= "self") or ins.op == "FunctionRef" then visit(ins.target) end
            end
        end
    end
    for _, export in ipairs(program.exports) do
        function_names[export.target] = function_names[export.target] or M.name(export.name)
        definitions[#definitions + 1] = {target = export.target, name = M.name(export.name), storage = ""}
        visit(export.target)
    end
    for _, id in pairs(program.callable_targets or {}) do visit(id) end
    for id in ipairs(program.functions) do
        if reachable[id] and not function_names[id] then
            function_names[id] = "wordfn_" .. id
            definitions[#definitions + 1] = {target = id, name = function_names[id], storage = "static "}
        end
    end
    local function header(definition)
        local fn, parameters = program.functions[definition.target], {}
        if fn.receiver then parameters[#parameters + 1] = ctype(fn.receiver.type) .. " *" .. v(fn.receiver.id) end
        if fn.captures then parameters[#parameters + 1] = ctype(fn.captures.type) .. " " .. v(fn.captures.id) end
        for _, p in ipairs(fn.parameters) do parameters[#parameters + 1] = ctype(p.type) .. " " .. v(p.id) end
        return definition.storage .. ctype(fn.result) .. " " .. definition.name .. "(" ..
            (#parameters > 0 and table.concat(parameters, ", ") or "void") .. ")"
    end
    for _, definition in ipairs(definitions) do out[#out + 1] = header(definition) .. ";" end
    -- Borrowed callback bundles live in the caller's activation: an actual
    -- receiver pointer plus immutable captures copied by value, never a heap.
    local function bundle(id) return "wordbound_" .. id end
    for id, fn in ipairs(program.functions) do
        if reachable[id] and fn.captures then
            out[#out + 1] = "typedef struct { " ..
                (fn.receiver and (ctype(fn.receiver.type) .. " *receiver; ") or "") ..
                ctype(fn.captures.type) .. " captures; } " .. bundle(id) .. ";"
        end
    end
    local adapters = {}
    local function adapter(ins) return "wordadapter_" .. ins.target .. "_" .. ctype(ins.type) end
    for id, fn in ipairs(program.functions) do
        if reachable[id] then for _, block in ipairs(fn.blocks) do for _, ins in ipairs(block.instructions) do
            if ins.op == "FunctionRef" and not Model.callable(ins.type).code and not adapters[adapter(ins)] then
                adapters[adapter(ins)] = true
                local abi, parameters, args = Model.callable(ins.type), {"void *environment"}, {}
                local callee = program.functions[ins.target]
                if callee.receiver then
                    args[#args + 1] = callee.captures and ("((" .. bundle(ins.target) .. " *)environment)->receiver") or
                        ("(" .. ctype(callee.receiver.type) .. " *)environment")
                end
                if callee.captures then args[#args + 1] = "((" .. bundle(ins.target) .. " *)environment)->captures" end
                for i, p in ipairs(abi.parameters) do
                    parameters[#parameters + 1] = ctype(p.type) .. " a" .. i; args[#args + 1] = "a" .. i
                end
                out[#out + 1] = "static " .. ctype(abi.result) .. " " .. adapter(ins) .. "(" .. table.concat(parameters, ", ") ..
                    ") { (void)environment; " .. (Model.primitive(abi.result) == "Unit" and "" or "return ") ..
                    function_names[ins.target] .. "(" .. table.concat(args, ", ") .. "); }"
            end
        end end end
    end
    local function closure_api(name, t, seen, internal)
        local abi = Model.callable(t)
        if not abi or not abi.code then return end
        local id = program.callable_targets[t]
        local parameters, args = {}, {}
        parameters[#parameters + 1] = ctype(t) .. " closure"
        if abi.environment then args[#args + 1] = (abi.value_environment and "&" or "") .. "closure.environment" end
        for i, p in ipairs(abi.parameters) do
            parameters[#parameters + 1] = ctype(p.type) .. " a" .. i; args[#args + 1] = "a" .. i
        end
        out[#out + 1] = ctype(abi.result) .. (internal and " wordcalltype_" or " wordcall_") .. name .. "(" ..
            table.concat(parameters, ", ") .. ") { (void)closure; " ..
            (Model.primitive(abi.result) == "Unit" and "" or "return ") .. function_names[id] ..
            "(" .. table.concat(args, ", ") .. "); }"
        if not internal and Model.callable(abi.result) then
            out[#out + 1] = "typedef " .. ctype(abi.result) .. " wordresult_call_" .. name .. ";"
            seen = seen or {}; seen[t] = true
            if not seen[abi.result] then closure_api(name .. "_result", abi.result, seen) end
        end
    end
    for _, t in ipairs(order) do closure_api(ctype(t), t, nil, true) end
    for _, export in ipairs(program.exports) do
        local t = program.functions[export.target].result
        closure_api(escape(export.name), t)
        local record = Model.record(t)
        if record then for _, name in ipairs(record.runtime_order) do
            closure_api(escape(export.name) .. "_" .. escape(name), record.fields[name])
        end end
    end
    out[#out + 1] = ""
    for _, definition in ipairs(definitions) do
        local fn = program.functions[definition.target]
        out[#out + 1] = header(definition)
        out[#out + 1] = "{"
        if fn.receiver then out[#out + 1] = "    (void)" .. v(fn.receiver.id) .. ";" end
        if fn.captures then out[#out + 1] = "    (void)" .. v(fn.captures.id) .. ";" end
        for _, p in ipairs(fn.parameters) do out[#out + 1] = "    (void)" .. v(p.id) .. ";" end
        local function tail_call(block)
            if block.exit.op ~= "Return" then return nil end
            local instructions = block.instructions
            local index = #instructions
            while index > 0 and instructions[index].op ~= "Call" do index = index - 1 end
            local last = instructions[index]
            if not last or last.target ~= "self" or borrowing_calls[last] then return nil end
            -- Keep the exact incoming receiver; never replace it with caller-local storage.
            if fn.receiver and (last.receiver.root ~= fn.receiver.id or #last.receiver.path ~= 0) then return nil end
            if index == #instructions and block.exit.value == last.id then return last, index end
            if not Model.record(last.type) then return nil end
            -- Record returns can forward through copies, projections and exact reconstruction.
            -- Every post-call operand must originate in that return; stores/calls/arithmetic forbid rewriting.
            local origins = {[last.id] = {path = {}}}
            local function project(node, name)
                if not node then return nil end
                if node.path then
                    local path = {table.unpack(node.path)}; path[#path + 1] = name
                    return {path = path}
                end
                return node.fields[name]
            end
            for i = index + 1, #instructions do
                local ins, node = instructions[i]
                if ins.op == "Local" then node = origins[ins.initial]
                elseif ins.op == "Load" then
                    node = origins[ins.root]
                    for _, name in ipairs(ins.path) do node = project(node, name) end
                elseif ins.op == "Construct" then
                    node = {fields = {}}
                    for name, id in pairs(ins.fields) do
                        if not origins[id] then return nil end
                        node.fields[name] = origins[id]
                    end
                else return nil end
                if not node then return nil end
                origins[ins.id] = node
            end
            local function unchanged(node, t, path)
                if not node then return false end
                if node.path then
                    if #node.path ~= #path then return false end
                    for i, name in ipairs(path) do if node.path[i] ~= name then return false end end
                    return true
                end
                local def = Model.record(t)
                if not def then return false end
                for _, name in ipairs(def.runtime_order) do
                    local ft = def.fields[name]
                    if Model.primitive(ft) ~= "Unit" then
                        local child = {table.unpack(path)}; child[#child + 1] = name
                        if not unchanged(node.fields[name], ft, child) then return false end
                    end
                end
                return true
            end
            if unchanged(origins[block.exit.value], last.type, {}) then return last, index end
        end
        local looping = false
        for _, block in ipairs(fn.blocks) do if tail_call(block) then looping = true end end
        local function call(ins)
            local args = {}
            if ins.receiver then args[#args + 1] = "&(" .. target(ins.receiver, fn) .. ")" end
            if ins.captures then args[#args + 1] = v(ins.captures) end
            for _, id in ipairs(ins.args) do args[#args + 1] = v(id) end
            if ins.op == "IndirectCall" then
                table.insert(args, 1, v(ins.callable) .. ".environment")
                return v(ins.callable) .. ".invoke(" .. table.concat(args, ", ") .. ")"
            end
            local name = ins.target == "self" and definition.name or function_names[ins.target]
            return name .. "(" .. table.concat(args, ", ") .. ")"
        end
        local function emit_block(id, indent)
            local block = fn.blocks[id]
            local tail, tail_index = tail_call(block)
            for i = 1, (tail_index or (#block.instructions + 1)) - 1 do
                local ins = block.instructions[i]
                if ins.op == "Pow" then
                    local base, exponent, result = "wordbase_" .. ins.id, "wordexp_" .. ins.id, v(ins.id)
                    out[#out + 1] = indent .. "uint32_t " .. result .. " = UINT32_C(1);"
                    out[#out + 1] = indent .. "uint32_t " .. base .. " = " .. v(ins.args[1]) .. ", " .. exponent .. " = " .. v(ins.args[2]) .. ";"
                    out[#out + 1] = indent .. "while (" .. exponent .. " != 0) {"
                    out[#out + 1] = indent .. "    if ((" .. exponent .. " & UINT32_C(1)) != 0) " .. result ..
                        " = (uint32_t)((uint64_t)" .. result .. " * (uint64_t)" .. base .. ");"
                    out[#out + 1] = indent .. "    " .. exponent .. " >>= 1;"
                    out[#out + 1] = indent .. "    " .. base .. " = (uint32_t)((uint64_t)" .. base .. " * (uint64_t)" .. base .. ");"
                    out[#out + 1] = indent .. "}"
                    out[#out + 1] = indent .. "(void)" .. result .. ";"
                elseif ins.op == "Store" then out[#out + 1] = indent .. target(ins, fn) .. " = " .. v(ins.value) .. ";"
                elseif (ins.op == "Call" or ins.op == "IndirectCall") and Model.primitive(ins.type) == "Unit" then
                    out[#out + 1] = indent .. call(ins) .. ";"
                else
                    local expression
                    if ins.op == "Div" or ins.op == "Mod" then
                        out[#out + 1] = indent .. "if (" .. v(ins.args[2]) .. " == 0) abort();"
                    end
                    if ins.op == "Constant" then expression = literal(ins.type, ins.value)
                    elseif ins.op == "Local" then expression = v(ins.initial)
                    elseif ins.op == "Load" then expression = target(ins, fn)
                    elseif ins.op == "Call" or ins.op == "IndirectCall" then expression = call(ins)
                    elseif ins.op == "FunctionRef" then
                        local abi = Model.callable(ins.type)
                        if abi.code then
                            expression = "(" .. ctype(ins.type) .. "){ " ..
                                (ins.receiver and (".environment = " .. (abi.value_environment and "(" or "&(") .. target(ins.receiver, fn) .. ")") or ".word_empty = 0") .. " }"
                        else
                            local environment = ins.receiver and ("&(" .. target(ins.receiver, fn) .. ")") or "NULL"
                            if ins.captures then
                                local name = "wordenv_" .. ins.id
                                out[#out + 1] = indent .. bundle(ins.target) .. " " .. name .. " = {" ..
                                    (ins.receiver and (".receiver = " .. environment .. ", ") or "") ..
                                    ".captures = " .. v(ins.captures) .. "};"
                                environment = "&" .. name
                            end
                            expression = "(" .. ctype(ins.type) .. "){.invoke = " .. adapter(ins) .. ", .environment = " .. environment .. "}"
                        end
                    elseif ins.op == "Compare" then
                        local operator = ({eq = "==", lt = "<", le = "<="})[ins.predicate]
                        expression = v(ins.args[1]) .. " " .. operator .. " " .. v(ins.args[2])
                    elseif ins.op == "Construct" then
                        local fields = {}
                        for _, name in ipairs(Model.record(ins.type).runtime_order) do
                            if ins.fields[name] then fields[#fields + 1] = "." .. M.field_name(name) .. " = " .. v(ins.fields[name]) end
                        end
                        if #fields == 0 then fields[1] = ".word_empty = 0" end
                        expression = "(" .. ctype(ins.type) .. "){ " .. table.concat(fields, ", ") .. " }"
                    else
                        local operator = ({Add = "+", Sub = "-", Mul = "*", Div = "/", Mod = "%",
                            And = "&", Or = "|", Xor = "^", Shl = "<<", Shr = ">>"})[ins.op]
                        expression = "(uint32_t)((uint64_t)" .. v(ins.args[1]) .. " " .. operator .. " (uint64_t)" .. v(ins.args[2]) .. ")"
                        if ins.op == "Shl" or ins.op == "Shr" then
                            expression = "(" .. v(ins.args[2]) .. " >= UINT32_C(32) ? UINT32_C(0) : " .. expression .. ")"
                        end
                    end
                    out[#out + 1] = indent .. ctype(ins.type) .. " " .. v(ins.id) .. " = " .. expression .. ";"
                    out[#out + 1] = indent .. "(void)" .. v(ins.id) .. ";"
                end
            end
            if tail then
                -- Borrow checking excludes arguments that could refer to this activation.
                -- Snapshot every next argument before replacing any current parameter.
                if fn.captures then
                    out[#out + 1] = indent .. ctype(fn.captures.type) .. " wordnext_captures = " .. v(tail.captures) .. ";"
                end
                for i, parameter in ipairs(fn.parameters) do
                    out[#out + 1] = indent .. ctype(parameter.type) .. " wordnext_" .. i .. " = " .. v(tail.args[i]) .. ";"
                end
                if fn.captures then out[#out + 1] = indent .. v(fn.captures.id) .. " = wordnext_captures;" end
                for i, parameter in ipairs(fn.parameters) do
                    out[#out + 1] = indent .. v(parameter.id) .. " = wordnext_" .. i .. ";"
                end
                out[#out + 1] = indent .. "continue;"
            elseif block.exit.op == "Branch" then
                out[#out + 1] = indent .. "if (" .. v(block.exit.condition) .. ") {"
                emit_block(block.exit.yes, indent .. "    ")
                out[#out + 1] = indent .. "} else {"
                emit_block(block.exit.no, indent .. "    ")
                out[#out + 1] = indent .. "}"
            else
                out[#out + 1] = block.exit.value and (indent .. "return " .. v(block.exit.value) .. ";") or indent .. "return;"
            end
        end
        if looping then out[#out + 1] = "    for (;;) {" end
        emit_block(1, looping and "        " or "    ")
        if looping then out[#out + 1] = "    }" end
        out[#out + 1] = "}"; out[#out + 1] = ""
    end
    return table.concat(out, "\n")
end

return M
