-- extract.lua: turn compiled stencils into C data for the JIT.
--   luajit extract.lua stencils_cache.o stencils_cache_order.txt stencils_cache.h
-- Reads an x86-64 ELF relocatable object (one function per section) and
-- emits each stencil's machine code plus the relocations that refer to holes.
local OBJ, ORDER, OUT = arg[1], arg[2], arg[3]
assert(OBJ and ORDER and OUT, "usage: extract.lua file.o order.txt out.h")

local f = assert(io.open(OBJ, "rb")); local elf = f:read("*a"); f:close()
assert(elf:sub(1, 4) == "\127ELF" and elf:byte(5) == 2, "not an ELF64 file")
-- These ELF fields are file offsets, sizes, indices and small relocation addends.
-- Decode split r_info fields below rather than passing a packed uint64 through
-- a Lua number. Reject any other field above the exact integer range of doubles.
local function unpack_fields(format, data, position)
  local values = {}
  for kind, digits in format:gmatch("([IiB])(%d*)") do
    local bytes = kind == "B" and 1 or assert(tonumber(digits))
    assert(position + bytes - 1 <= #data, "truncated ELF field")
    local negative = kind == "i" and data:byte(position + bytes - 1) >= 128
    local value = 0
    for i = bytes - 1, 0, -1 do
      local byte = data:byte(position + i)
      value = value * 256 + (negative and 255 - byte or byte)
    end
    assert(value <= 9007199254740991, "ELF field exceeds exact Lua integer range")
    values[#values + 1] = negative and -value - 1 or value
    position = position + bytes
  end
  values[#values + 1] = position
  return unpack(values)
end
local u = string.unpack or unpack_fields

local shoff = u("<I8", elf, 0x28 + 1)
local shentsize, shnum, shstrndx = u("<I2I2I2", elf, 0x3A + 1)
local sec = {}
for i = 0, shnum - 1 do
  local o = shoff + i * shentsize + 1
  local name, typ, _, _, off, size, link, info = u("<I4I4I8I8I8I8I4I4", elf, o)
  sec[i] = { name = name, type = typ, off = off, size = size, link = link, info = info }
end
local function cstr(tab, at)
  local s = sec[tab]; local p = s.off + at + 1
  return elf:sub(p, elf:find("\0", p, true) - 1)
end
for i = 0, shnum - 1 do sec[i].sname = cstr(shstrndx, sec[i].name) end

-- symbols
local syms, symtab = {}, nil
for i = 0, shnum - 1 do if sec[i].type == 2 then symtab = i end end
assert(symtab, "no symbol table")
local st = sec[symtab]
for i = 0, math.floor(st.size / 24) - 1 do
  local name, info, _, shndx, value, size = u("<I4BBI2I8I8", elf, st.off + i * 24 + 1)
  syms[i] = { name = cstr(st.link, name), info = info, shndx = shndx, value = value, size = size }
end

-- relocations, grouped by the section they apply to
local rels = {}
for i = 0, shnum - 1 do
  local s = sec[i]
  if s.type == 4 then   -- SHT_RELA
    local list = rels[s.info] or {}; rels[s.info] = list
    for k = 0, math.floor(s.size / 24) - 1 do
      local off, rtype, symbol, addend = u("<I8I4I4i8", elf, s.off + k * 24 + 1)
      list[#list + 1] = { off = off, type = rtype, sym = syms[symbol], addend = addend }
    end
  end
end

local HOLES = { HOLE_NEXT = 0, HOLE_TAKEN = 1, HOLE_IMM = 2, HOLE_FINAL = 3, HOLE_IMM2 = 4, HOLE_STATE = 5, HOLE_ERROR = 6, HOLE_BIAS = 7 }
local RTYPE = { [1] = "R64", [2] = "RPC32", [4] = "RPC32", [10] = "R32", [11] = "R32", [14] = "R8" }

local funcs = {}
for _, s in pairs(syms) do if s.info % 16 == 2 then funcs[s.name] = s end end

local order = {}
for line in io.lines(ORDER) do if line ~= "" then order[#order + 1] = line end end

local out, bytes_total, tails = {}, 0, 0
local function W(x) out[#out + 1] = x end
W("/* generated by extract.lua from " .. OBJ .. " */")
W("enum { RPC32, R32, R64, R8 };")
W("enum { HOLE_NEXT, HOLE_TAKEN, HOLE_IMM, HOLE_FINAL, HOLE_IMM2, HOLE_STATE, HOLE_ERROR, HOLE_BIAS };")
W("typedef struct { uint16_t off; uint8_t kind, hole; int32_t addend; } Reloc;")
W("typedef struct { const uint8_t *code; uint16_t len, nrel; const Reloc *rel; } Stencil;")
local entries = {}
for idx, name in ipairs(order) do
  local fn = assert(funcs[name], "missing stencil " .. name)
  local s = sec[fn.shndx]
  local code = elf:sub(s.off + fn.value + 1, s.off + fn.value + fn.size)
  local list = {}
  for _, r in ipairs(rels[fn.shndx] or {}) do
    local hole = HOLES[r.sym.name]
    assert(hole, ("%s: relocation against unexpected symbol '%s'"):format(name, r.sym.name))
    assert(RTYPE[r.type], ("%s: unsupported relocation type %d"):format(name, r.type))
    list[#list + 1] = r
  end
  table.sort(list, function(a, b) return a.off < b.off end)
  -- a trailing "jmp HOLE_NEXT" is dropped: the next stencil is placed right after
  local len, keep = #code, list
  local last = list[#list]
  if last and last.sym.name == "HOLE_NEXT" and last.off == len - 4 and code:byte(len - 4) == 0xE9 then
    len = len - 5; keep = {}
    for i = 1, #list - 1 do keep[i] = list[i] end
    tails = tails + 1
  end
  bytes_total = bytes_total + len
  local hex = {}
  for i = 1, len do hex[#hex + 1] = ("0x%02x"):format(code:byte(i)) end
  W(("static const uint8_t c%d[] = {%s};"):format(idx - 1, len > 0 and table.concat(hex, ",") or "0"))
  if #keep > 0 then
    local rs = {}
    for _, r in ipairs(keep) do
      rs[#rs + 1] = ("{%d,%s,%d,%d}"):format(r.off, RTYPE[r.type], HOLES[r.sym.name], r.addend)
    end
    W(("static const Reloc r%d[] = {%s};"):format(idx - 1, table.concat(rs, ",")))
  end
  entries[#entries + 1] = ("{c%d,%d,%d,%s}"):format(idx - 1, len, #keep, #keep > 0 and "r" .. (idx - 1) or "0")
end
W(("static const Stencil stencils[%d] = {\n  %s\n};"):format(#entries, table.concat(entries, ",\n  ")))
local o = assert(io.open(OUT, "w")); o:write(table.concat(out, "\n"), "\n"); o:close()
io.stderr:write(("%s: %d stencils, %d bytes of code, %d tail jumps removed\n"):format(OUT, #entries, bytes_total, tails))
