local directory=(arg[0]:match('^(.*)/[^/]*$') or '.')
package.path=directory..'/?.lua;'..package.path
local manifest=require('opcodes')
local output=assert(arg[1],'output header required')
local ops=manifest.ops
assert(#ops<=256,'opcode byte exhausted')
local kind_name={
  [manifest.kind.NORMAL]='K_NORMAL',[manifest.kind.BRANCH]='K_BRANCH',[manifest.kind.CALL]='K_CALL',
  [manifest.kind.RET]='K_RET',[manifest.kind.HALT]='K_HALT',[manifest.kind.ABORT]='K_ABORT',
  [manifest.kind.OPI]='K_OPI',[manifest.kind.OPC]='K_OPC',[manifest.kind.BRI]='K_BRI',
  [manifest.kind.TCALL]='K_TCALL',[manifest.kind.INTERNAL]='K_INTERNAL',[manifest.kind.MEMORY]='K_MEMORY',
  [manifest.kind.ICALL]='K_ICALL',[manifest.kind.ITCALL]='K_ITCALL',[manifest.kind.EXT]='K_EXT',[manifest.kind.FCALL]='K_FCALL',
  [manifest.kind.JMP32]='K_JMP32',[manifest.kind.SWITCH]='K_SWITCH'
}
local out={'/* generated by tools/gen_opcodes.lua from tools/opcodes.lua */','#pragma once','enum {'}
for i,op in ipairs(ops) do
  if i-1==manifest.legacy_count then out[#out+1]=('  OP_LEGACY_COUNT = %d,'):format(manifest.legacy_count) end
  out[#out+1]=('  OP_%s = %d,'):format(op.name,i-1)
end
out[#out+1]=('  OP_COUNT = %d'):format(#ops)
out[#out+1]='};'
out[#out+1]='enum { K_NORMAL, K_BRANCH, K_CALL, K_RET, K_HALT, K_ABORT, K_OPI, K_OPC, K_BRI, K_TCALL, K_INTERNAL, K_MEMORY, K_ICALL, K_ITCALL, K_EXT, K_FCALL, K_JMP32, K_SWITCH };'
out[#out+1]='enum {'
for i,x in ipairs(manifest.ext_ops) do out[#out+1]=('  EXT_%s = %d,'):format(x.name,i-1) end
out[#out+1]=('  EXT_COUNT = %d'):format(#manifest.ext_ops)
out[#out+1]='};'
local ext_lengths={} for i=1,256 do ext_lengths[i]=0 end
for i,x in ipairs(manifest.ext_ops) do ext_lengths[i]=x.len end
out[#out+1]='static const unsigned char ext_len[256] = {'..table.concat(ext_lengths,',')..'};'
local ext_names={} for i,x in ipairs(manifest.ext_ops) do ext_names[i]=('"%s"'):format(x.name) end
out[#out+1]='static const char *const ext_name[EXT_COUNT] = {'..table.concat(ext_names,',')..'};'
local lengths,kinds,names={},{},{}
for _,op in ipairs(ops) do lengths[#lengths+1]=op.len; kinds[#kinds+1]=op.kind; names[#names+1]=('"%s"'):format(op.name) end
out[#out+1]='static const unsigned char op_len[] = {'..table.concat(lengths,',')..'};'
out[#out+1]='static const unsigned char op_kind[] = {'..table.concat(kinds,',')..'};'
out[#out+1]='static const char *const op_name[] = {'..table.concat(names,',')..'};'
out[#out+1]='enum { M_NONE, M_ALLOC, M_FREE, M_FLOAD, M_FSTORE, M_FADDR, M_GLOAD, M_GSTORE, M_GADDR, M_PLOAD, M_PSTORE, M_XLOAD, M_INDEX, M_COPY };'
out[#out+1]='typedef struct { unsigned char action, width, to_b, sign; } abc_memory_op;'
out[#out+1]='static const abc_memory_op op_memory[OP_COUNT] = {'
for i,op in ipairs(ops) do
  local m=op.mem
  if m then out[#out+1]=('  [OP_%s] = {%d,%d,%d,%d},'):format(op.name,m.action,m.width,m.to_b,m.sign) end
end
out[#out+1]='};'
local f=assert(io.open(output,'wb')); assert(f:write(table.concat(out,'\n'),'\n')); assert(f:close())
